export default [
  {
    title: "Digital Marketing Masterclass - 23 Courses in 1",
    image: require("../assets/imgs/img-11.jpg"),
    subtitle: "Black Jacket",
    review: "4.5",
    cta: "View article",
    price: "200",
    discountPrice: "200",
  },
  {
    title: "Life Coaching Certification Course (Beginner to Advanced)",
    image: require("../assets/imgs/img-14.jpg"),
    subtitle: "Nelson Farnandis",
    review: "4.5",
    cta: "View article",
    price: "200",
    discountPrice: "200",
  },

  {
    title: "Complete Blender Creator: Learn 3D Modelling for Beginners",
    image: require("../assets/imgs/img-10.jpg"),
    subtitle: "Grant Auth",
    review: "4.5",
    cta: "View article",
    price: "1200",
    discountPrice: "700",
  },
  {
    title: "Photography Masterclass: A Complete Guide to Photography",
    image: require("../assets/imgs/img-13.jpg"),
    subtitle: "Samuel, Jockson",
    review: "4.5",
    cta: "View article",
    price: "500",
    discountPrice: "149",
  },
  {
    title: "Java Programming Masterclass for Software Developers",
    image: require("../assets/imgs/img-3.jpg"),
    subtitle: "Akul, David Warner",
    review: "4.5",
    cta: "View article",
    price: "1200",
    discountPrice: "999",
  },

  {
    title: "An Entire MBA in 1 Course:Award Winning Business School Prof",
    image: require("../assets/imgs/img-15.jpg"),
    subtitle: "Robin Dias",
    review: "4.5",
    cta: "View article",
    price: "800",
    discountPrice: "600",
  },
];
